### PR TITLE
feat: init biorecer context

### PR DESCRIPTION
**Pull request by junjou**
Init a biorecer context to be enriched during the project

### CODE REVIEW

**Comment by bobeal** [comment]
from my experience, it's not so good to give the name of the project to the directory. Better use a name that reminds the business domain of the project.

**Comment by junjou** [comment]
> from my experience, it's not so good to give the name of the project to the directory. Better use a name that reminds the business domain of the project.

updated

**Comment by bobeal** [comment]
seems you have an extra `s` in resources

**Comment by junjou** [comment]
> seems you have an extra `s` in resources

😢 yes

**Review by bobeal — APPROVED** [review]

**Pull request merged**
