### PR TITLE
Clone and clean SDM Environment context

### PR DESCRIPTION
**Pull request by junjou**
see: 
https://raw.githubusercontent.com/smart-data-models/dataModel.Environment/master/context.jsonld

### CODE REVIEW

**Comment by bobeal** [comment]
Can't really say if good or not. So merge and let's see.

**Comment by junjou** [comment]
> Can't really say if good or not. So merge and let's see.

I just cloned it and removed all the core context attributes (id, type, location...)

**Comment by bobeal** [comment]
> > Can't really say if good or not. So merge and let's see.
> 
> I just cloned it and removed all the core context attributes (id, type, location...)

Yes, saw that. But there is the whole context, how it integrates with other things in the compound context,... and no clue if it will fix the problem (which I don't really know about). So I can't say anything but try it ...

**Comment by junjou** [comment]
> Yes, saw that. But there is the whole context, how it integrates with other things in the compound context,... and no clue if it will fix the problem (which I don't really know about). So I can't say anything but try it ...

Ok, let's see then. 
PS: I need an approval before merging

**Pull request merged**
