### PR TITLE
add missing Device terms

### PR DESCRIPTION
**Pull request by ddumet**
In addition to temperature, relativeHumidity and co2, Pilze Sensors also reports sensor specific information:
* rssi (Receive Signal Strenght Indicator,
* battery voltage
* lora signal-noise ratio

There's no terms related to these properties in Fiware smartData models. Adding these terms into a "graced-various.jsonld" file for now. Need to follow up at some point with a pull request to smart data models.
graced-various.jsonld intent is to contain (temporarily) such  missing terms, when no EGM domain context (such as Agrifood or weather) exists.

### CODE REVIEW

**Comment by bobeal** [comment]
We are already using these terms, @AHABID should know where they are defined.

**Comment by ddumet** [comment]
BatteryVoltage is in aquaculture.jsonld and in airQuality-context.jsonld.
Can I re-use (include) one of this context into graced.jsonld then ?

**Comment by ddumet** [comment]
And Lorasnr is in airQuality-context.jsonld as well.
So I guess I should use airQuality-context.jsonld in Graced context then , correct ?

**Comment by AHABID** [comment]
My opinion here is to create a new folder "device" for example, and to put on it all new attributes. This will be a nice step toward organizing contexts.

**Comment by bobeal** [comment]
> My opinion here is to create a new folder "device" for example, and to put on it all new attributes. This will be a nice step toward organizing contexts.

we could call it same as the target data model we'll finally contribute it into.

**Comment by ddumet** [comment]
Happy with that if Benoît is ok as well, as it follows the trend of weather and agrifood recently created.
The question is how does it/does it not "compete" with smartdata models (which also have weather, device, agrifood) ?
We agree that at some point they need to be merged, yes ?

**Comment by bobeal** [comment]
> Happy with that if Benoît is ok as well, as it follows the trend of weather and agrifood recently created. The question is how does it/does it not "compete" with smartdata models (which also have weather, device, agrifood) ? We agree that at some point they need to be merged, yes ?

Definitely!

**Review by AHABID — APPROVED** [review]

**Comment by ddumet** [comment]
* Remove the graced-various.jsonld context
* Create a device datamodels directory with a device context, containing currently missing terms, i.e. batteryVoltage and loraSNR.
* Add this context into graced context.

**Review by bobeal — APPROVED** [review]

**Pull request merged**
